{
  "jobs": {
    "build": {
      "name": "Build on ${{ matrix.platform }}",
      "runs-on": "${{ matrix.platform }}-${{ matrix.version }}",
      "steps": [
        {
          "uses": "actions/checkout@v4"
        },
        {
          "run": "mkdir artifact"
        },
        {
          "id": "haskell",
          "uses": "haskell-actions/setup@v2",
          "with": {
            "cabal-version": "3.10.2.1",
            "ghc-version": "9.8.1"
          }
        },
        {
          "run": "cabal sdist --output-dir artifact"
        },
        {
          "run": "cabal configure --enable-optimization=2 --enable-tests --flags=pedantic --jobs"
        },
        {
          "run": "cat cabal.project.local"
        },
        {
          "run": "cp cabal.project.local artifact"
        },
        {
          "run": "cabal freeze"
        },
        {
          "run": "cat cabal.project.freeze"
        },
        {
          "run": "cp cabal.project.freeze artifact"
        },
        {
          "run": "cabal outdated --v2-freeze-file cabal.project.freeze"
        },
        {
          "uses": "actions/cache@v4",
          "with": {
            "key": "${{ matrix.platform }}-${{ hashFiles('cabal.project.freeze') }}",
            "path": "${{ steps.haskell.outputs.cabal-store }}",
            "restore-keys": "${{ matrix.platform }}-"
          }
        },
        {
          "run": "cabal build --only-download"
        },
        {
          "run": "cabal build --only-dependencies"
        },
        {
          "run": "cabal build"
        },
        {
          "run": "cp $( cabal list-bin cabal-gild ) artifact"
        },
        {
          "uses": "svenstaro/upx-action@v2",
          "with": {
            "files": "artifact/cabal-gild${{ matrix.extension }}"
          }
        },
        {
          "uses": "actions/upload-artifact@v4",
          "with": {
            "name": "cabal-gild-${{ matrix.platform }}-${{ github.sha }}",
            "path": "artifact"
          }
        },
        {
          "run": "cabal run -- cabal-gild-test-suite"
        }
      ],
      "strategy": {
        "matrix": {
          "include": [
            {
              "platform": "macos",
              "version": 13
            },
            {
              "platform": "ubuntu",
              "version": 22.04
            },
            {
              "extension": ".exe",
              "platform": "windows",
              "version": 2022
            }
          ]
        }
      }
    },
    "cabal": {
      "name": "Cabal",
      "runs-on": "ubuntu-22.04",
      "steps": [
        {
          "uses": "actions/checkout@v4"
        },
        {
          "run": "cabal check"
        }
      ]
    },
    "hlint": {
      "name": "HLint",
      "runs-on": "ubuntu-22.04",
      "steps": [
        {
          "uses": "actions/checkout@v4"
        },
        {
          "uses": "haskell-actions/hlint-setup@v2",
          "with": {
            "version": 3.8
          }
        },
        {
          "uses": "haskell-actions/hlint-run@v2",
          "with": {
            "fail-on": "status"
          }
        }
      ]
    },
    "ormolu": {
      "name": "Ormolu",
      "runs-on": "ubuntu-22.04",
      "steps": [
        {
          "uses": "actions/checkout@v4"
        },
        {
          "uses": "haskell-actions/run-ormolu@v14",
          "with": {
            "version": "0.7.3.0"
          }
        }
      ]
    }
  },
  "name": "Workflow",
  "on": {
    "push": null,
    "schedule": [
      {
        "cron": "0 0 * * 1"
      }
    ]
  }
}
